map $http_x_forwarded_proto $forwarded_proto {
  default $http_x_forwarded_proto;
  "" $scheme;
}
map $http_x_forwarded_port $forwarded_port {
  default $http_x_forwarded_port;
  "" $server_port;
}

server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api/ {
    proxy_pass http://[[ backend_artifact_id ]]:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $forwarded_proto;
  }

  location /actuator/ {
    proxy_pass http://[[ backend_artifact_id ]]:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $forwarded_proto;
  }

[% if auth_mode == "bundled" %]
  location = /auth {
    return 301 /auth/;
  }

  location /auth/ {
    proxy_pass http://keycloak:8080;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Port $forwarded_port;
    proxy_set_header X-Forwarded-Proto $forwarded_proto;
  }
[% endif %]
}
